msg: This is from git hub..

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: test123
        url: jdbc:mysql://localhost:3306/sbms27
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
